DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	email VARCHAR(64) NOT NULL,
	password CHAR(128) NOT NULL,
	salt CHAR(64) NOT NULL,
	UNIQUE(email),
	PRIMARY KEY(id)	
);

CREATE TABLE profile
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userId INT UNSIGNED NOT NULL,
	firstName VARCHAR(32) NOT NULL,
	lastName VARCHAR(32) NOT NULL,
	birthday DATE,
	specialNeeds TINYINT UNSIGNED NOT NULL,
	INDEX(userId),
	PRIMARY KEY(id),
	FOREIGN KEY(userId) REFERENCES user(id)
);

CREATE TABLE flight
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	flightNumber MEDIUMINT UNSIGNED NOT NULL,
	origin CHAR(3) NOT NULL,
	destination CHAR(3) NOT NULL,
	numberSeats MEDIUMINT UNSIGNED NOT NULL,
	departureTime TIME NOT NULL,
	PRIMARY KEY(id)
	
);

CREATE TABLE ticket
(
	userId INT UNSIGNED NOT NULL,
	flightId INT UNSIGNED NOT NULL,
	seat CHAR(6) NOT NULL,
	cost DECIMAL(7,2) NOT NULL,
	INDEX(flightId),
	INDEX(userId),
	PRIMARY KEY(flightId, userId),
	FOREIGN KEY(userId) REFERENCES user(id),
	FOREIGN KEY(flightId) REFERENCES flight(id)
);